version: "3.8"
services:
  mysql:
    image: mysql:8.0
    container_name: MYAPP
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: MYAPP_db
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data: